config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'todo_items/updateStatus'
  get 'todo_items/destroy'
  get 'todo_lists/destroy'
  resources :todo_lists do
  resources :todo_items
  end
  root 'todo_lists#index'
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  validates :content, presence: true

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
		  validates :title, presence: true, length: { maximum: 20 }
		  belongs_to :user
		  has_many :todo_items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
protect_from_forgery  
end

app/controllers/todo_items_controller.rb
	class TodoItemsController < ApplicationController
		def create
			@todo_list = TodoList.find(params[:todo_list_id])
			@todo_item = @todo_list.todo_items.create(params[:todo_item].permit(:content))
			respond_to do |format|
				if @todo_item.save
					format.html { redirect_to @todo_list, notice: 'Todo item was successfully created.' }
					format.json { render :show, status: :created, location: @todo_list }
				else
					format.html { render :new }
					format.json { render json: @todo_item.errors, status: :unprocessable_entity }
				end
			end
		end
		def new
			@todo_list = TodoList.find(params[:todo_list_id])
			@todo_item = @todo_list.todo_items.create(:content => params[:todo_item])
		end
		def update
			@todo_list = TodoList.find(params[:todo_list_id])
			@todo_item = @todo_list.todo_items.update(status: true)

		end

		def destroy
			puts "*********************************"
			puts params[:id]
			puts TodoItem.find(params[:id])
			TodoItem.find(params[:id]).destroy
			flash[:success] = "User deleted"
			redirect_to :back
		end

		def updateStatus
			puts "hello"
			@todo_list = TodoList.find(params[:list])
			@todo_item = TodoItem.find(params[:id])
			status = params[:status]
			puts status
			status1 = (status == "true") ? false : true;
			puts status1
			@todo_item = @todo_item.update(status: status1)
			redirect_to :back
		end
	end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update]

  def index
    if user_signed_in?
      @todo_lists = current_user.todo_lists
    else
      @todo_lists = TodoList.all
    end
  end

  def show
  end


  def new
    @todo_list = current_user.todo_lists.build
  end

  def edit
  end

  def create
    @todo_list = current_user.todo_lists.build(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, noticecutom:  'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end
  

  def destroy
    TodoList.find(params[:id]).destroy
    flash.now[:success] = "Destroyed!"
    redirect_to :back
end

def set_todo_list
  puts params[:id]
  @todo_list = TodoList.find(params[:id])
end

def todo_list_params
  params.require(:todo_list).permit(:title)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/_header.html.erb
<title>To-Do Application</title>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">

      <a class="navbar-brand"><i class="ion-ios-book-outline"></i> TODO APPLICATION <i class="ion-ios-book-outline"></i>
</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li><%= link_to "Your Todo List", root_path %></li>
      <li><%= link_to "Edit Account", edit_user_registration_path %></li>

      <li>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %> 

      </li>



      <% else %>
      <li>
        <%= link_to('Login', new_user_session_path)  %>  

      </li>
      <li>
        <%= link_to('Register', new_user_registration_path)  %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'application', media: 'all',
  'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
      <![endif]-->
    </head>
    <body>
      <%= render 'layouts/header' %>
      <div>
       <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
        <p class="alert-error"><%= alert %></p>        
      </div>
      <%= yield %>
    </body>
    </html>

app/views/todo_items/_form.html.erb
<div class="container">
<%= form_for([@todo_list,@todo_list.todo_items.build]) do |f| %>
<% if @todo_item.errors.any? %>
<div id="container">
  <div id="error_explanation">
    <ul class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% @todo_item.errors.full_messages.each do |message| %>
      <li class="alert-error"><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :content%><br>
    <div class="control-group">

      <%= f.text_field :content , class: "form-control" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/todo_items/_todo_item.html.erb
<%=todo_item.content%>

app/views/todo_items/new.html.erb
<div class="container">
<legend>Add A Todo Item</legend>
</div><%= render 'form' %>

app/views/todo_lists/_form.html.erb
<div class="container">
  <%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
     <div id="alert-error">
    <ul class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% @todo_list.errors.full_messages.each do |message| %>
      <li class="alert-error"><%= message %></li>
      <% end %>
    </ul>
      </div>
      <%else%>
        <p><%= notice %></p>

  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>

    <%= f.text_field :title , class: "form-control"%>
  </div>
  <div class="form-actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/todo_lists/edit.html.erb
<div class="container">
<legend>Edit To-do List</legend>
</div>
<%= render 'form' %>

app/views/todo_lists/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>
  <% if user_signed_in? %>
    <legend>Your To-do List</legend>

  <%if @todo_lists %>

  <div class="container">
  </div>

  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <div >
          <th>Title</th>
          <th>Actions</th>
        </div>
      </tr>
    </thead>
    <tbody>
      <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.title%></td>
        <td><%= link_to(
          content_tag(
            :i,
            nil, 
            class: 'ion-ios-paper-outline action-icon',
            title: "show"
              ),
          todo_list,
          ) 
          %>
          <%= link_to(
            content_tag(
              :i,
              nil, 
              class: 'ion-ios-compose-outline action-icon',
                title: "edit"
                ),
            edit_todo_list_path(todo_list),
            ) 
            %>

            <%= link_to(
              content_tag(
                :i,
                nil, 
                class: 'ion-ios-trash-outline action-icon',
                title: "delete",
                
                  ),
              todo_list,
              method: :delete,
              data: { confirm: 'Are you sure to delete the list and its items?' }
              ) 
              %></td>

            </tr>

            <%end%>
            <br/>

            <p><%= link_to " Add New", new_todo_list_path, :class => "button", :method => :get %></p>
            <br/>

            <%else%>
            <p><%= link_to " Add New", new_todo_list_path, :class => "button", :method => :get %></p>

          </tbody>
        </table>

        <br>
        <%end %>
        <%else%>
        <br/>
        <center><h1 style="color:#2196f3">Sign in to view the content</h1></center>
        <%end%>
</div>

app/views/todo_lists/new.html.erb
<div class="container">
<legend>Your To-do List</legend>
</div>
<%= render 'form' %>

app/views/todo_lists/show.html.erb
<div class="container">
	<div class="form-group">
		<p>
			<strong>For Todo List:</strong>
			<legend><%= @todo_list.title %></legend>
		</p>
	</div>

	<%= link_to 'Add ToDo Item',  new_todo_list_todo_item_path(@todo_list) %>
	<br/>
	<br/>


	<%#= render @todo_list.todo_items%>
	<%if !@todo_list.todo_items.empty?%>
	<table class="table table-hover table-striped table-condensed">
		<tr>
			<div >
				<th>Content</th>
				<th>Actions</th>
			</div>
			<% @todo_list.todo_items.each do |todo| %>
			<tr>
				<%#puts todo.status%>
				<%if !todo.status%>
				<td><%=  todo.content%></td>

				<td><%= link_to(
					content_tag(
						:i,
						nil, 
						class: 'ion-ios-checkmark-outline action-icon',
							title: "done"
							), 
					:controller => "todo_items",
					:action => "updateStatus",
					:id => todo.id,
					:status => todo.status,
					:list => @todo_list.id
					) 
					%>
					<%= link_to(
						content_tag(
							:i,
							nil, 
							class: 'ion-ios-trash-outline action-icon',
								title: "delete"
								),
						:controller => "todo_items",
						:action => "destroy",
						:id => todo.id,
						) 
						%></td>

						<%else%>
						<td style="color:#009900"><%=  todo.content%></td>

						<td><%= link_to(
							content_tag(
								:i,
								nil, 
								class: 'ion-ios-close-outline action-icon',
									title: "undone"
									), 
							:controller => "todo_items",
							:action => "updateStatus",
							:id => todo.id,
							:status => todo.status,
							:list => @todo_list.id
							) 
							%>
							<%= link_to(
								content_tag(
									:i,
									nil, 
									class: 'ion-ios-trash-outline action-icon',
										title: "delete"
										), 

								:controller => "todo_items",
								:action => "destroy",
								:id => todo.id, 
								) 
								%></td>
							</i>
						</tr>
						<%end%>
						<%#= link_to 'Delete', todo_item_path(@todo_list,todo_items.id), :method=> :put %>
						<%end%>

					</tr>
				</table>
				<%end%>
</div>